spring:
  application:
    name: bi-backend
  # Dev environment by default (multi environment)
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
#    store-type: redis
    # 30 days expiration (timeout)
    timeout: 2592000
  # Datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bi_db
    username: root
    password: AQ31km7q5#Hc
  # Redis config
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch config
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # File Uploadgit
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 expiration (age)
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # Name of the entity field for logical deletion
      logic-delete-value: 1 # default 1
      logic-not-delete-value: 0 # default 0


# yu ai model service
yuapi:
  client:
    access-key: vgny2kxyu1ccww2bo4rip9ocs4qwa9lp
    secret-key: 063uofwyq9bn1g0lx0070vgcrwi5ya3q