package com.becoze.biback.model.entity;

import com.baomidou.mybatisplus.annotation.*;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Chart
 * @TableName chart
 */
@TableName(value ="chart")
@Data
public class Chart implements Serializable {
    /**
     * id
     */
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /**
     * Name
     */
    private String name;

    /**
     * Purpose
     */
    private String goal;

    /**
     * Raw Chart Data
     */
    private String chartData;

    /**
     * Chart Type e.g. pie-chart, line-chart
     */
    private String chartType;

    /**
     * Chart generated by AI
     */
    private String genChart;

    /**
     * Text/explanation generated by AI
     */
    private String genResult;

    /**
     * Chart status. wait, running, succeed, failed
     */
    private String status;

    /**
     * Execution message
     */
    private String execMessage;

    /**
     * Creator user id
     */
    private Long userId;

    /**
     * Create Time
     */
    private Date createTime;

    /**
     * Update Time
     */
    private Date updateTime;

    /**
     * is delete
     */
    @TableLogic
    private Integer isDelete;

    @TableField(exist = false)
    private static final long serialVersionUID = 1L;
}