-- Create table
create database if not exists bi_db;

-- Use table
use bi_db;

-- user table
create table if not exists user
(
    id           bigint auto_increment comment 'id' primary key,
    userAccount  varchar(256)                           not null comment 'User Account',
    userPassword varchar(512)                           not null comment 'User Password',
    userName     varchar(256)                           null comment 'User Name',
    userAvatar   varchar(1024)                          null comment 'User Avatar',
    userRole     varchar(256) default 'user'            not null comment 'User role：user/admin',
    createTime   datetime     default CURRENT_TIMESTAMP not null comment 'Create Time',
    updateTime   datetime     default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment 'Update Time',
    isDelete     tinyint      default 0                 not null comment 'is delete',
    index idx_userAccount (userAccount)
) comment 'User' collate = utf8mb4_unicode_ci;

-- chart table
create table if not exists chart
(
    id           bigint auto_increment comment 'id' primary key,
    goal		 text null comment 'Purpose',
    chartData	 text null comment 'Raw Chart Data',
    chartType	 varchar(128) null comment 'Chart Type e.g. pie-chart, line-chart',
    genChart 	 text null comment 'Chart generated by AI',
    genResult	 text null comment 'Text/explanation generated by AI',
    userId		 bigint	null comment 'Creator user id',
    createTime   datetime     default CURRENT_TIMESTAMP not null comment 'Create Time',
    updateTime   datetime     default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment 'Update Time',
    isDelete     tinyint      default 0                 not null comment 'is delete'
) comment 'chart' collate = utf8mb4_unicode_ci;